Planner/Controllers/AnalyticsController.cs
/*using Microsoft.AspNetCore.Mvc;
using Planner.Models.ViewModels;
using Planner.Repositories;
using Planner.Repositories.Interface;
using Planner.Service;

namespace Planner.Controllers
{
    public class AnalyticsController : Controller
    {
        private readonly IAnalyticsRepository analyticsRepository;
        Research research = new Research();
        
        public AnalyticsController (IAnalyticsRepository analyticsRepository)
        {
            this.analyticsRepository = analyticsRepository;
        }
        public async Task<IActionResult> Analytics()
        {
            var patients = await analyticsRepository.GetPatient();
            var analyticsRequest = new AnalyticsRequest
            {
               StartDay = patients.Min(patient => patient.RegistrationDay),
               EndDay = patients.Max(patient => patient.RegistrationDay),
               AvgMBK = patients.Average(patient => patient.MBK)
            };
            analyticsRequest.NameResearchList = research.nameResearch.Keys.ToList();
            analyticsRequest.CountResearch = patients
             .GroupBy(patient => patient.Research)
             .ToDictionary(
                  group => group.Key,
                  group => group.Count()
             );
            return View(analyticsRequest);
        }

      *//*  [HttpPost]
        public async Task<IActionResult> YourAction(AnalyticsRequest analytics)
        {
            var patients = await analyticsRepository.GetPatient();
            var updAnalytics = new AnalyticsRequest
            {
                StartDay = analytics.StartDay,
                EndDay = analytics.EndDay,
                Research = analytics.Research,
                NameResearchList = analytics.NameResearchList,
                AvgMBK = patients.Average(patient => patient.MBK)
            };
            updAnalytics.CountResearch = patients
             .GroupBy(patient => patient.Research)
             .ToDictionary(
                  group => group.Key,
                  group => group.Count()
             );
            return Json(new { labels = updAnalytics.Research, data = updAnalytics.AvgMBK });
        }*//*
    }
}
*/


using Microsoft.AspNetCore.Mvc;
using Planner.Models.Domain;
using Planner.Models.ViewModels;
using Planner.Repositories;
using Planner.Repositories.Interface;
using Planner.Service;

namespace Planner.Controllers
{
    public class AnalyticsController : Controller
    {
        private readonly IAnalyticsRepository analyticsRepository;
        Research research = new Research();

        public AnalyticsController(IAnalyticsRepository analyticsRepository)
        {
            this.analyticsRepository = analyticsRepository;
        }

        // Ваш текущий метод действия для отображения страницы аналитики
        public async Task<IActionResult> Analytics()
        {
            var patients = await analyticsRepository.GetPatient();
            var analyticsRequest = new AnalyticsRequest
            {
                StartDay = patients.Min(patient => patient.RegistrationDay),
                EndDay = patients.Max(patient => patient.RegistrationDay),
                AvgMBK = patients.Average(patient => patient.MBK)
            };
            analyticsRequest.NameResearchList = research.nameResearch.Keys.ToList();
            analyticsRequest.CountResearch = patients
             .GroupBy(patient => patient.Research)
             .ToDictionary(
                  group => group.Key,
                  group => group.Count()
             );
            return View(analyticsRequest);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateChart(AnalyticsRequest request)
        {
            // Используйте методы из вашего репозитория для получения данных для графика
            IEnumerable<Patient> patients;

            if (!string.IsNullOrEmpty(request.Research)) // Если выбрано конкретное исследование
            {
                patients = await analyticsRepository.GetPatientResearch(request.StartDay, request.EndDay, request.Research);
            }
            else // Если не выбрано конкретное исследование
            {
                patients = await analyticsRepository.GetPatient(request.StartDay, request.EndDay);
            }

            // В этом примере я просто возвращаю средние значения MBK для всех пациентов за выбранный период времени
            // Вы должны настроить эту логику в соответствии с вашими требованиями
            var newDataForChart = patients.Select(patient => patient.MBK).ToList();

            return Json(newDataForChart);
        }
    }
}

Planner/Controllers/PatientController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Planner.Models.Domain;
using Planner.Models.ViewModels;
using Planner.Repositories.Interface;
using Planner.Service;
using System.Collections.Generic;

namespace Planner.Controllers
{

    public class PatientController : Controller
    {
        private readonly IPatientRepository patientRepository;
        private readonly IWeekDayRepository weekDayRepository;
        private CalculationMBK calculationMBK = new CalculationMBK();
        private Research research = new Research();

        public PatientController(IPatientRepository patientRepository, IWeekDayRepository weekDayRepository)
        {
            this.patientRepository = patientRepository;
            this.weekDayRepository = weekDayRepository;
        }

        [HttpGet]
        public IActionResult Add(DateTime registrationDay, Guid weekDayId, double quantityMBK)
        {
            List <string> list = new List<string>();
            foreach (var research in research.radiationResearch)
            {
                foreach (var minMax in research.Value)
                {
                    if (minMax.Key == "Min")
                    {
                        var minValue = minMax.Value;
                        if (quantityMBK >= minValue)
                        {
                            list.Add(research.Key.ToString());
                        }
                    }
                }
            }
            var addPatientRequest = new AddPatientRequest
            {
                PatientWeekDayId = weekDayId,
                RegistrationDay = registrationDay,
                NameResearchList = list,
                QuantityMBK = quantityMBK
            };
            return View(addPatientRequest);
        }

        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddPatientRequest addPatientRequest)
        {    
            var patient = new Patient
            {
                Id = new Guid(),
                WeekDayId = addPatientRequest.PatientWeekDayId,
                RegistrationDay = addPatientRequest.RegistrationDay,
                Name = addPatientRequest.Name,
                Surname = addPatientRequest.Surname,
                Research = addPatientRequest.Research,
                BirthDay = addPatientRequest.BirthDay,
            };

            var updWeekDay = await weekDayRepository.GetAsync(patient.WeekDayId);
            patient.MBK = calculationMBK.PatientMbK(patient);
            await patientRepository.AddAsync(patient);
            await weekDayRepository.UpdateAsync(updWeekDay);
           
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid weekDayId)
        {
            var patient = await patientRepository.GetAsync(weekDayId);
            if (patient != null)
            {
               
                var editPatientRequest = new EditPatientRequest
                {
                    Id = patient.Id,
                    Name = patient.Name,
                    Surname = patient.Surname,
                    RegistrationDay = patient.RegistrationDay,
                    Research = patient.Research,
                    PatientWeekDayId = patient.WeekDayId,
                };

                return View(editPatientRequest);
            }

            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditPatientRequest editPatientRequest)
        {
            var patient = new Patient
            {
                Id = editPatientRequest.Id,
                Name = editPatientRequest.Name,
                Surname = editPatientRequest.Surname,
                RegistrationDay = editPatientRequest.RegistrationDay,
                Research = editPatientRequest.Research,
            };

            var updatePatient = await patientRepository.UpdateAsync(patient);
            if (updatePatient != null)
            {
                //Show success
                return RedirectToAction("Index", "Home");
            }
            else
            {
                // Show failed
            }

            return RedirectToAction("Edit", new { id = editPatientRequest.Id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditPatientRequest editPatientRequest)
        {
            var deletePatient = await patientRepository.DeleteAsync(editPatientRequest.Id);

            if (deletePatient != null)
            {
                var updWeekDay = await weekDayRepository.GetAsync(editPatientRequest.PatientWeekDayId);
                await weekDayRepository.UpdateAsync(updWeekDay);
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Edit", new { id = editPatientRequest.Id });
        }
    }
}   

Planner/Controllers/WeekDayController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using Planner.Models.Domain;
using Planner.Models.ViewModels;
using Planner.Repositories.Interface;
using Planner.Service;

namespace Planner.Controllers
{
    public class WeekDayController : Controller
    {
        private readonly IWeekDayRepository weekDayRepository;
        private readonly IPatientRepository patientRepository;
        private readonly IServices services;
        private CalculationMBK calculationMBK = new CalculationMBK();
        private Generator generator = new Generator();

        public WeekDayController(IWeekDayRepository weekDayRepository, IPatientRepository patientRepository, IServices services)
        {
            this.weekDayRepository = weekDayRepository;
            this.patientRepository = patientRepository;
            this.services = services;
        }

        [HttpGet]
        public IActionResult List()
        {
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var occupiedDates = await weekDayRepository.GetAllAsync();
            var dates = occupiedDates.Select(d => d.Day.ToString("yyyy-MM-dd")).ToList();

            ViewBag.OccupiedDates = dates;
            return View();
        }


        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddWeekDayRequest addWeekDayRequest)
        {
            var weekDay = new WeekDay
            {
                Day = addWeekDayRequest.Day,
            };
            var added = await weekDayRepository.GetAllAsync();
            foreach(var add in added)
            {
                if(add.Day == addWeekDayRequest.Day)
                {
                    return RedirectToAction("List");
                }
            }
            weekDay.ActivityDay = generator.ActivityDay(addWeekDayRequest.Day);
            weekDay.QuantityMbK = generator.ValMbkForGenDay(weekDay.ActivityDay);
            weekDay.RemainderMBK = calculationMBK.RemainderMBK(weekDay);
            weekDay.ArrivalDay = generator.ArrivalDay(weekDay.ActivityDay, addWeekDayRequest.Day);
            await weekDayRepository.AddAsync(weekDay);
            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid weekDayId)
        {
            var weekDay = await weekDayRepository.GetAsync(weekDayId);

            if (weekDay != null)
            {
                var editWeekDay = new EditWeekDayRequest
                {
                    Id = weekDay.Id,
                    ArrivalDay = weekDay.ArrivalDay,
                    ActivityDay = weekDay.ActivityDay,
                    RemainderMBK = weekDay.RemainderMBK,
                    RegisteredPatients = weekDay.RegisteredPatients,
                    Day = weekDay.Day,
                };
                var patients = await services.GetPatientForDay(weekDay.Id);
                foreach (var patient in patients)
                {
                    patient.MBK = calculationMBK.PatientMbK(patient);
                }
                editWeekDay.Patients = (ICollection<Patient>)patients;
                return View(editWeekDay);

            }
            return View(null);
        }

        [HttpPost]
        [ActionName("Edit")]
        public async Task<IActionResult> Edit(EditWeekDayRequest editWeekDayRequest)
        {
            var weekDay = new WeekDay
            {
                Id = editWeekDayRequest.Id,
                Day = editWeekDayRequest.Day,
               // ArrivalDay = editWeekDayRequest.ArrivalDay,
                RegisteredPatients = editWeekDayRequest.RegisteredPatients,
                RemainingPatients = editWeekDayRequest.RemainingPatients
            };

            var patients = await services.GetPatientForDay(weekDay.Id);
            weekDay.Patients = (ICollection<Patient>)patients;
            weekDay.ActivityDay = generator.ActivityDay(weekDay.Day);
            weekDay.QuantityMbK = generator.ValMbkForGenDay(weekDay.ActivityDay);
           // weekDay.ArrivalDay = generator.ArrivalDay(weekDay.Day);
            var updateWeekDay = await weekDayRepository.UpdateAsync(weekDay);
            if (updateWeekDay != null)
            {
                return RedirectToAction("List");
            }
            return RedirectToAction("Edit", new { id = editWeekDayRequest.Id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditWeekDayRequest editWeekDayRequest)
        {
            var deleteweekDay = await weekDayRepository.DeleteAsync(editWeekDayRequest.Id);
            if (deleteweekDay != null)
            {
                await services.DeletePatientsForDay(editWeekDayRequest.Id);
                return RedirectToAction("List");
            }
            return RedirectToAction("Edit", new { id = editWeekDayRequest.Id });
        }
        [HttpPost]   
        public async Task<IActionResult> Calculated (EditWeekDayRequest editWeekDayRequest)
        {
            var weekDay = new WeekDay
            {
                Id = editWeekDayRequest.Id,
                Day = editWeekDayRequest.Day,
                ArrivalDay = editWeekDayRequest.ArrivalDay,
                RegisteredPatients = editWeekDayRequest.RegisteredPatients,
                RemainingPatients = editWeekDayRequest.RemainingPatients,
            };
            var patients = await services.GetPatientForDay(weekDay.Id);
            weekDay.Patients = (ICollection<Patient>)patients;
            weekDay.ActivityDay = generator.ActivityDay(weekDay.Day);
            weekDay.QuantityMbK = generator.ValMbkForGenDay(weekDay.ActivityDay);
            weekDay.RemainderMBK = calculationMBK.RemainderMBK(weekDay);
           
            weekDay.Patients = calculationMBK.CalculatedResult(weekDay);

                weekDay.RemainderMBK = calculationMBK.CalculatedRemainderMBK(weekDay);
            
           /* foreach (var patient in weekDay.Patients)
            {
                patient.MBK = calculationMBK.CalculatedResult(patient, weekDay);
                await patientRepository.UpdateAsync(patient);
                weekDay.RemainderMBK = calculationMBK.CalculatedRemainderMBK(weekDay);
            }*/
            await services.UpdateMBK(weekDay);
            return RedirectToAction("List");
        }


        [HttpPost]
        public IActionResult UpdateChart(DateTime selectedDate, string selectedResearch)
        {
            // Здесь вы можете использовать выбранную дату и исследование для получения новых данных для графика
            // Например, вы можете использовать ваш репозиторий для получения данных
            var newDataForChart = GetDataForChart(selectedDate, selectedResearch);

            // Верните данные в формате JSON
            return Json(newDataForChart);
        }

        private object GetDataForChart(DateTime selectedDate, string selectedResearch)
        {
            // Здесь должна быть логика для получения новых данных для графика на основе выбранной даты и исследования
            // Например, вы можете использовать ваш сервис или репозиторий для получения этих данных

            // В этом примере я просто возвращаю случайные данные для иллюстрации
            var random = new Random();
            var newData = new List<int>();
            for (int i = 0; i < 7; i++)
            {
                newData.Add(random.Next(10, 100)); // Просто случайные данные
            }

            return new { newData };
        }


    }
}

Planner/Views/Home/Analytics.cshtml
@*



@model List<Planner.Models.Domain.WeekDay>
@using Microsoft.AspNetCore.Mvc.ViewFeatures


@{
    ViewData["Title"] = "Home Page";
    Layout = null; 
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.min.js"></script>

<div style="width: 80%; margin: auto;">
    <canvas id="myChart"></canvas>
</div>

<script>
    var days = @Html.Raw(Json.Serialize((Model.Select(w => w.Day.ToShortDateString()))));
    var activityDays = @Html.Raw(Json.Serialize((Model.Select(w => w.ActivityDay))));
   // var countRessearch = @Html.Raw(Json.Serialize(Model.Select(x => x.NumberOfPatients)));
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: days,
            datasets: [{
                label: 'Activity Days',
                data: activityDays,
                backgroundColor: 'rgba(75, 192, 192, 0.2)',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
</script>
*@

@model List<Planner.Models.Domain.WeekDay>
@using Microsoft.AspNetCore.Mvc.ViewFeatures

@{
    ViewData["Title"] = "Home Page";
    Layout = null;
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.min.js"></script>
<script src="https://unpkg.com/htmx.org/dist/htmx.min.js"></script>

<div style="width: 80%; margin: auto;">
    <canvas id="myChart"></canvas>
</div>

<button hx-post="@Url.Action("UpdateChart", "WeekDayController")" hx-target="#myChart">Update Chart</button>

<script>
    var days = @Html.Raw(Json.Serialize(Model.Select(w => w.Day.ToShortDateString())));
    var activityDays = @Html.Raw(Json.Serialize(Model.Select(w => w.ActivityDay)));
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: days,
            datasets: [{
                label: 'Activity Days',
                data: activityDays,
                backgroundColor: 'rgba(75, 192, 192, 0.2)',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
</script>

Planner/Views/Home/Index.cshtml
@model List<Planner.Models.Domain.WeekDay>

@{
    ViewData["Title"] = "Home Page";
   
}


<style>
    .containerMain {
        display: flex;
        justify-content: flex-start;
        flex-wrap: wrap; /* Allow wrapping to the next line if there are too many items */
        gap: 10px; /* Add some space between the items */
    }

    .no-underline-hover {
        text-decoration: none;
        transition: font-size 0.2s;
    }

        .no-underline-hover:hover {
            font-size: 1.1em;
        }

    th, td {
        padding: 5px;
        font-size: 12px;
    }

    .patientInfo {
        transition: transform 0.3s ease;
    }

        .patientInfo:hover {
            transform: scale(1.1);
            background: #9D8D8F;
            cursor: pointer;
        }

    body {
        background: linear-gradient(to left, #f0f2f5, #e6e9ed, #9D8D8F );
    }


    .containerEmpty {
        display: flex;
        justify-content: left;
        align-items: flex-start;
        padding: 50px;
    }

    .containerBox {
        border: 1px solid #000;
        width: 420px;
        height: auto;
        padding: 5px;
    }

    .box {
        border: 1px solid #000;
        width: 200px;
        height: 400px;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        text-align: center;
        padding-bottom: 20px;
    }

    .addButton {
        font-size: 2rem;
        border: none;
        background: none;
        cursor: pointer;
        color: #000;
        transition: transform 0.3s ease;
    }

        .addButton:hover {
            transform: scale(1.2);
        }

    .p {
        margin-bottom: 15px;
    }

    .scroll-container {
        overflow-y: auto;
        max-height: 400px;
    }

        .scroll-container::-webkit-scrollbar {
            width: 5px;
        }

        .scroll-container::-webkit-scrollbar-track {
            border-radius: 5px;
        }

        .scroll-container::-webkit-scrollbar-thumb {
            background-color: #888;
            border-radius: 10px;
        }

            .scroll-container::-webkit-scrollbar-thumb:hover {
                background-color: #555;
            }
</style>


@*/***********************  Form for add button     ************************/*@

<div class="container col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-5 ry-5">
        <div class="col-12 col-lg-6">
            <h1 class="display-5 fw-bold lh-1 mb-3">
                Laboratorium Radionuclids
            </h1>
            <p class="lead">
                Registering patients
            </p>
        </div>
        <div class="col-12 col-lg-6">
            <img src="https://images.pexels.com/photos/1193743/pexels-photo-1193743.jpeg?auto=compress&cs=tinysrgb&w=600"
                 alt="Week Day - Laboratorium radiations"
                 class="d-block mx-lg-auto img-fluid" width="300" />
        </div>
    </div>
</div>


@********************************************   Form for main window    *******************8*@
<div class="containerMain">
    <div class="containerEmpty">
        <div class="box">
            <p class="p">Добавить день</p>
            <button class="addButton">
                <a asp-area=""
                   asp-controller="WeekDay"
                   asp-action="Add">
                    <img src="/image/add.png" />
                </a>
            </button>
        </div>
    </div>
    @if (Model != null && Model.Any())
    {
        @foreach (var weekDay in Model)
        {
            <div class="containerBox">
                <div class="row justify-content-center">
                    <div class="mb-3 box-shadow">
                        <h3 style="text-align: center; color: #dc3545" class="mb-2 ps-2">
                            @{
                                var dayOfWeek = weekDay.Day.ToString("dddd");
                                dayOfWeek = char.ToUpper(dayOfWeek[0]) + dayOfWeek.Substring(1);
                            }
                            @dayOfWeek:  @weekDay.Day.ToShortDateString()</h3>
                        <h3 style="font-size: 16px" class="mb-2 ps-3">Activity Day: @weekDay.ActivityDay</h3>
                        <h3 style="font-size: 16px" class="mb-2 ps-3">Quantity MBK: @weekDay.QuantityMbK</h3>
                        <h3 style="font-size: 16px" class="mb-2 ps-3">Remainder MBK: @weekDay.RemainderMBK</h3>
                        <h3 style="font-size: 16px" class="mb-2 ps-3">Arrival Day: @weekDay.ArrivalDay.ToShortDateString()</h3>
                        <div class="scroll-container">
                            <div class="container py-3 ps-3">
                                <h3 style="font-size: 20px; text-align: center">Patients</h3>
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col">№</th>
                                            <th scope="col">Name</th>
                                            <th scope="col">Surname</th>
                                            <th scope="col">Birth day</th>
                                            <th scope="col">Research</th>
                                            <th scope="col">MBK</th>
                                        </tr>
                                    </thead>

                                    @if (weekDay.Patients != null)
                                    {
                                        int count = 1;
                                        @foreach (var people in weekDay.Patients)
                                        {
                                            <tbody id="editPatients" class="table-group-divider">
                                                <tr class="patientInfo" data-weekday-id="@weekDay.Id" data-registration-day="@weekDay.Day.ToString("dd.mm.yyyy")" data-patient-id="@people.Id"
                                                data-researches ="@people.Research">

                                                    <td>@count</td>
                                                    <td>@people.Name</td>
                                                    <td>@people.Surname</td>
                                                    <td>@people.BirthDay.ToShortDateString()</td>
                                                    <td>@people.Research</td>
                                                    <td>@people.MBK</td>
                                                </tr>
                                            </tbody>
                                            count++;
                                        }
                                    }
                                    else
                                    {
                                        <tfoot>No Patient found!</tfoot>
                                    }
                                </table>
                            </div>
                            <div class="mb-1 ps-2">
                                <button type="submit" class="btn btn-dark" style="font-size: 12px; padding: 5px 10px;">
                                    <a class="text-white no-underline-hover"
                                       asp-area=""
                                       asp-controller="Patient"
                                       asp-action="Add"
                                       asp-route-weekDayId="@weekDay.Id"
                                       asp-route-registrationDay="@weekDay.Day.ToString("yyyy-MM-dd")"
                                       asp-route-quantityMBK="@weekDay.RemainderMBK">
                                                Add Patient
                                    </a>
                                </button>
                                <button type="submit" class="btn btn-dark" style="font-size: 12px; padding: 5px 10px;"
                                    asp-area=""
                                    asp-controller="WeekDay"
                                    asp-action="Calculated">
                                        Calculated MBK
                                </button>

                                <button type="submit" class="btn btn-danger ms-2" id="calculated" style="font-size: 12px; padding: 5px 10px;">
                                    <a class="text-white no-underline-hover"
                                       asp-area=""
                                       asp-controller="WeekDay"
                                       asp-action="Edit"
                                       asp-route-weekDayId="@weekDay.Id">
                                                Edit Day
                                    </a>
                                </button>
                              
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
    
</div>




<script>
    document.querySelectorAll(".patientInfo").forEach(function (row) {
        row.addEventListener("click", function (event) {
            // Получаем значения из атрибутов данных
            var weekDayId = row.getAttribute("data-patient-id");
            var registrationDay = row.getAttribute("data-registration-day");
            var reseaerches = row.getAttribute("data-researches");
          //  var patientId = row.getAttribute("data-patient-id");

          //  var weekDayId = row.getAttribute("data-weekday-id");
          //  var registrationDay = row.getAttribute("data-registration-day");
          //  var patientId = row.getAttribute("data-patient-id");

            // Формируем URL для перехода
            var url = `/Patient/Edit?weekDayId=${encodeURIComponent(weekDayId)}&day=${encodeURIComponent(registrationDay)}`;

            // Переходим на другую страницу
            window.location.href = url;
        });
    });

    document.getElementById("calculated").forEach(function (row) {
        row.addEventListener("click", function (event) {
            // Получаем значения из атрибутов данных
            var weekDayId = row.getAttribute("data-patient-id");
          //  var registrationDay = row.getAttribute("data-registration-day");
          //  var reseaerches = row.getAttribute("data-researches");
            //  var patientId = row.getAttribute("data-patient-id");

            //  var weekDayId = row.getAttribute("data-weekday-id");
            //  var registrationDay = row.getAttribute("data-registration-day");
            //  var patientId = row.getAttribute("data-patient-id");

            // Формируем URL для перехода
            var url = `/Patient/Edit?weekDayId=${encodeURIComponent(weekDayId)}&day=${encodeURIComponent(registrationDay)}`;

            // Переходим на другую страницу
            window.location.href = url;
        });
    });

</script>