Planner/Controllers/AnalyticsController.cs
/*using Microsoft.AspNetCore.Mvc;
using Planner.Models.ViewModels;
using Planner.Repositories;
using Planner.Repositories.Interface;
using Planner.Service;

namespace Planner.Controllers
{
    public class AnalyticsController : Controller
    {
        private readonly IAnalyticsRepository analyticsRepository;
        Research research = new Research();
        
        public AnalyticsController (IAnalyticsRepository analyticsRepository)
        {
            this.analyticsRepository = analyticsRepository;
        }
        public async Task<IActionResult> Analytics()
        {
            var patients = await analyticsRepository.GetPatient();
            var analyticsRequest = new AnalyticsRequest
            {
               StartDay = patients.Min(patient => patient.RegistrationDay),
               EndDay = patients.Max(patient => patient.RegistrationDay),
               AvgMBK = patients.Average(patient => patient.MBK)
            };
            analyticsRequest.NameResearchList = research.nameResearch.Keys.ToList();
            analyticsRequest.CountResearch = patients
             .GroupBy(patient => patient.Research)
             .ToDictionary(
                  group => group.Key,
                  group => group.Count()
             );
            return View(analyticsRequest);
        }

      *//*  [HttpPost]
        public async Task<IActionResult> YourAction(AnalyticsRequest analytics)
        {
            var patients = await analyticsRepository.GetPatient();
            var updAnalytics = new AnalyticsRequest
            {
                StartDay = analytics.StartDay,
                EndDay = analytics.EndDay,
                Research = analytics.Research,
                NameResearchList = analytics.NameResearchList,
                AvgMBK = patients.Average(patient => patient.MBK)
            };
            updAnalytics.CountResearch = patients
             .GroupBy(patient => patient.Research)
             .ToDictionary(
                  group => group.Key,
                  group => group.Count()
             );
            return Json(new { labels = updAnalytics.Research, data = updAnalytics.AvgMBK });
        }*//*
    }
}
*/


using Microsoft.AspNetCore.Mvc;
using Planner.Models.Domain;
using Planner.Models.ViewModels;
using Planner.Repositories;
using Planner.Repositories.Interface;
using Planner.Service;

namespace Planner.Controllers
{
    public class AnalyticsController : Controller
    {
        private readonly IAnalyticsRepository analyticsRepository;
        Research research = new Research();

        public AnalyticsController(IAnalyticsRepository analyticsRepository)
        {
            this.analyticsRepository = analyticsRepository;
        }

        // Ваш текущий метод действия для отображения страницы аналитики
        public async Task<IActionResult> Analytics()
        {
            var patients = await analyticsRepository.GetPatient();
            var analyticsRequest = new AnalyticsRequest
            {
                StartDay = patients.Min(patient => patient.RegistrationDay),
                EndDay = patients.Max(patient => patient.RegistrationDay),
                AvgMBK = patients.Average(patient => patient.MBK)
            };
            analyticsRequest.NameResearchList = research.nameResearch.Keys.ToList();
            analyticsRequest.CountResearch = patients
             .GroupBy(patient => patient.Research)
             .ToDictionary(
                  group => group.Key,
                  group => group.Count()
             );
            return View(analyticsRequest);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateChart(AnalyticsRequest request)
        {
            // Используйте методы из вашего репозитория для получения данных для графика
            IEnumerable<Patient> patients;

            if (!string.IsNullOrEmpty(request.Research)) // Если выбрано конкретное исследование
            {
                patients = await analyticsRepository.GetPatientResearch(request.StartDay, request.EndDay, request.Research);
            }
            else // Если не выбрано конкретное исследование
            {
                patients = await analyticsRepository.GetPatient(request.StartDay, request.EndDay);
            }

            // В этом примере я просто возвращаю средние значения MBK для всех пациентов за выбранный период времени
            // Вы должны настроить эту логику в соответствии с вашими требованиями
            var newDataForChart = patients.Select(patient => patient.MBK).ToList();

            return Json(newDataForChart);
        }
    }
}

Planner/Controllers/WeekDayController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using Planner.Models.Domain;
using Planner.Models.ViewModels;
using Planner.Repositories.Interface;
using Planner.Service;

namespace Planner.Controllers
{
    public class WeekDayController : Controller
    {
        private readonly IWeekDayRepository weekDayRepository;
        private readonly IPatientRepository patientRepository;
        private readonly IServices services;
        private CalculationMBK calculationMBK = new CalculationMBK();
        private Generator generator = new Generator();

        public WeekDayController(IWeekDayRepository weekDayRepository, IPatientRepository patientRepository, IServices services)
        {
            this.weekDayRepository = weekDayRepository;
            this.patientRepository = patientRepository;
            this.services = services;
        }

        [HttpGet]
        public IActionResult List()
        {
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var occupiedDates = await weekDayRepository.GetAllAsync();
            var dates = occupiedDates.Select(d => d.Day.ToString("yyyy-MM-dd")).ToList();

            ViewBag.OccupiedDates = dates;
            return View();
        }


        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddWeekDayRequest addWeekDayRequest)
        {
            var weekDay = new WeekDay
            {
                Day = addWeekDayRequest.Day,
            };
            var added = await weekDayRepository.GetAllAsync();
            foreach(var add in added)
            {
                if(add.Day == addWeekDayRequest.Day)
                {
                    return RedirectToAction("List");
                }
            }
            weekDay.ActivityDay = generator.ActivityDay(addWeekDayRequest.Day);
            weekDay.QuantityMbK = generator.ValMbkForGenDay(weekDay.ActivityDay);
            weekDay.RemainderMBK = calculationMBK.RemainderMBK(weekDay);
            weekDay.ArrivalDay = generator.ArrivalDay(weekDay.ActivityDay, addWeekDayRequest.Day);
            await weekDayRepository.AddAsync(weekDay);
            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid weekDayId)
        {
            var weekDay = await weekDayRepository.GetAsync(weekDayId);

            if (weekDay != null)
            {
                var editWeekDay = new EditWeekDayRequest
                {
                    Id = weekDay.Id,
                    ArrivalDay = weekDay.ArrivalDay,
                    ActivityDay = weekDay.ActivityDay,
                    RemainderMBK = weekDay.RemainderMBK,
                    RegisteredPatients = weekDay.RegisteredPatients,
                    Day = weekDay.Day,
                };
                var patients = await services.GetPatientForDay(weekDay.Id);
                foreach (var patient in patients)
                {
                    patient.MBK = calculationMBK.PatientMbK(patient);
                }
                editWeekDay.Patients = (ICollection<Patient>)patients;
                return View(editWeekDay);

            }
            return View(null);
        }

        [HttpPost]
        [ActionName("Edit")]
        public async Task<IActionResult> Edit(EditWeekDayRequest editWeekDayRequest)
        {
            var weekDay = new WeekDay
            {
                Id = editWeekDayRequest.Id,
                Day = editWeekDayRequest.Day,
               // ArrivalDay = editWeekDayRequest.ArrivalDay,
                RegisteredPatients = editWeekDayRequest.RegisteredPatients,
                RemainingPatients = editWeekDayRequest.RemainingPatients
            };

            var patients = await services.GetPatientForDay(weekDay.Id);
            weekDay.Patients = (ICollection<Patient>)patients;
            weekDay.ActivityDay = generator.ActivityDay(weekDay.Day);
            weekDay.QuantityMbK = generator.ValMbkForGenDay(weekDay.ActivityDay);
           // weekDay.ArrivalDay = generator.ArrivalDay(weekDay.Day);
            var updateWeekDay = await weekDayRepository.UpdateAsync(weekDay);
            if (updateWeekDay != null)
            {
                return RedirectToAction("List");
            }
            return RedirectToAction("Edit", new { id = editWeekDayRequest.Id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditWeekDayRequest editWeekDayRequest)
        {
            var deleteweekDay = await weekDayRepository.DeleteAsync(editWeekDayRequest.Id);
            if (deleteweekDay != null)
            {
                await services.DeletePatientsForDay(editWeekDayRequest.Id);
                return RedirectToAction("List");
            }
            return RedirectToAction("Edit", new { id = editWeekDayRequest.Id });
        }
        [HttpPost]   
        public async Task<IActionResult> Calculated (EditWeekDayRequest editWeekDayRequest)
        {
            var weekDay = new WeekDay
            {
                Id = editWeekDayRequest.Id,
                Day = editWeekDayRequest.Day,
                ArrivalDay = editWeekDayRequest.ArrivalDay,
                RegisteredPatients = editWeekDayRequest.RegisteredPatients,
                RemainingPatients = editWeekDayRequest.RemainingPatients,
            };
            var patients = await services.GetPatientForDay(weekDay.Id);
            weekDay.Patients = (ICollection<Patient>)patients;
            weekDay.ActivityDay = generator.ActivityDay(weekDay.Day);
            weekDay.QuantityMbK = generator.ValMbkForGenDay(weekDay.ActivityDay);
            weekDay.RemainderMBK = calculationMBK.RemainderMBK(weekDay);
           
            weekDay.Patients = calculationMBK.CalculatedResult(weekDay);

                weekDay.RemainderMBK = calculationMBK.CalculatedRemainderMBK(weekDay);
            
           /* foreach (var patient in weekDay.Patients)
            {
                patient.MBK = calculationMBK.CalculatedResult(patient, weekDay);
                await patientRepository.UpdateAsync(patient);
                weekDay.RemainderMBK = calculationMBK.CalculatedRemainderMBK(weekDay);
            }*/
            await services.UpdateMBK(weekDay);
            return RedirectToAction("List");
        }


        [HttpPost]
        public IActionResult UpdateChart(DateTime selectedDate, string selectedResearch)
        {
            // Здесь вы можете использовать выбранную дату и исследование для получения новых данных для графика
            // Например, вы можете использовать ваш репозиторий для получения данных
            var newDataForChart = GetDataForChart(selectedDate, selectedResearch);

            // Верните данные в формате JSON
            return Json(newDataForChart);
        }

        private object GetDataForChart(DateTime selectedDate, string selectedResearch)
        {
            // Здесь должна быть логика для получения новых данных для графика на основе выбранной даты и исследования
            // Например, вы можете использовать ваш сервис или репозиторий для получения этих данных

            // В этом примере я просто возвращаю случайные данные для иллюстрации
            var random = new Random();
            var newData = new List<int>();
            for (int i = 0; i < 7; i++)
            {
                newData.Add(random.Next(10, 100)); // Просто случайные данные
            }

            return new { newData };
        }


    }
}

Planner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dispaly All Day</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  @*  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Planner.styles.css" asp-append-version="true" />*@
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
</head>
<body>
    <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratory Radionuclids</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Admin
                        </a>
                        <ul class="dropdown-menu">
                           <li>
                                <a class="dropdown-item"
                                   asp-area=""
                                   asp-controller="WeekDay"
                                   asp-action="Add">
                                    Add Day
                                </a>
                            </li>
                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="Home"
                                       asp-action="History">
                                        History Registred
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       asp-area=""
                                       asp-controller="Analytics"
                                       asp-action="Analytics">
                                        Analytics
                                    </a>
                                </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Laboratory Radionuclids - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>